openapi: 3.0.3
info:
  title: MoniRet APIs
  description: A set of APIs that allows FPs (Financial Providers) to agnostically participate for multiple Monime services including Merchant Payments, Agency Banking and seamless transfer of funds to other FPs.
  termsOfService: https://monime.io/legal/terms-of-service
  contact:
    name: Monime Developers
    url: https://github.com/monimesl
    email: dev@monime.io
  version: v1
servers:
  - url: https://test-fp.monimeapis.com/v1
paths:
  /self:
    get:
      tags:
        - Provider
      summary: Get Current Provider
      operationId: GetCurrentProvider
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Represents the status of the query operation, confirming if it was successful. This field is always true
                  messages:
                    type: array
                    items: {}
                    description: Contains a list of messages providing relevant information or feedback related to the query or operation
                  result:
                    $ref: "#/components/schemas/ProviderProvider"
  /transactions:
    get:
      tags:
        - Transaction
      parameters:
        - name: after
          in: query
          description: This cursor returns the next page of items in the result set.
          schema:
            maxLength: 2000
            type: string
            description: This cursor returns the next page of items in the result set.
            nullable: true
        - name: limit
          in: query
          description: The maximum number of items per page that should be retrieved from the result set.
          schema:
            maximum: 50
            minimum: 1
            type: integer
            description: The maximum number of items per page that should be retrieved from the result set.
            default: 10
        - name: endTime
          in: query
          schema:
            type: string
            format: date-time
            nullable: true
        - name: startTime
          in: query
          schema:
            type: string
            format: date-time
            nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Represents the status of the query operation, confirming if it was successful. This field is always true
                  messages:
                    type: array
                    items: {}
                    description: Contains a list of messages providing relevant information or feedback related to the query or operation
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        stage:
                          type: string
                        order:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            number:
                              type: string
                          nullable: true
                        merchant:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                        referredResource:
                          type: object
                          properties:
                            id:
                              type: string
                            type:
                              type: string
                            expireTime:
                              type: string
                              format: date-time
                              nullable: true
                            metadata:
                              maxProperties: 100
                              type: object
                              description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                              nullable: true
                        chargeMode:
                          type: string
                          nullable: true
                        createTime:
                          type: string
                          format: date-time
                        metadata:
                          maxProperties: 100
                          type: object
                          description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                          nullable: true
                    description: The list of items in the response
                    nullable: true
                  pagination:
                    type: object
                    properties:
                      count:
                        type: integer
                        description: The number of items in this page not the entire result set.
                      total:
                        type: integer
                        description: The total number of items in the entire result set.
                        nullable: true
                      prev:
                        type: string
                        description: This is a cursor pointing to the page of items just before the current one. Use with the 'after' query parameter in your next request to get the items that comes before this current page.
                        nullable: true
                      next:
                        type: string
                        description: This is a cursor pointing to the page of items just after the current one. Use with the 'after' query parameter in your next request to get the items that comes after this current page.
                        nullable: true
                    description: The pagination info associated with the response
  /transactions/{transactionId}:
    get:
      tags:
        - Transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Represents the status of the query operation, confirming if it was successful. This field is always true
                  messages:
                    type: array
                    items: {}
                    description: Contains a list of messages providing relevant information or feedback related to the query or operation
                  result:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      stage:
                        type: string
                      order:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          number:
                            type: string
                        nullable: true
                      merchant:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                      referredResource:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
                          expireTime:
                            type: string
                            format: date-time
                            nullable: true
                          metadata:
                            maxProperties: 100
                            type: object
                            description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                            nullable: true
                      chargeMode:
                        type: string
                        nullable: true
                      createTime:
                        type: string
                        format: date-time
                      metadata:
                        maxProperties: 100
                        type: object
                        description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                        nullable: true
                    description: The item for the response
    put:
      tags:
        - Transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
        - name: Monime-Signature
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  enum:
                    - INITIATE
                    - PAY
                  type: string
                data:
                  type: object
                  oneOf:
                    - type: object
                      properties:
                        alias:
                          type: string
                        metadata:
                          maxProperties: 100
                          type: object
                          description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                          nullable: true
                    - type: object
                      properties:
                        accountId:
                          type: string
                        txnId:
                          type: string
                        amount:
                          type: object
                          properties:
                            currency:
                              type: string
                              description: The [3-letter](https://en.wikipedia.org/wiki/ISO_4217) ISO currency code.
                            value:
                              type: integer
                              description: The value representation in the currency's minor unit. E.g. For 1 Leone (SLE 1), the value should be 100, denoting cents, the minor unit.
                        metadata:
                          maxProperties: 100
                          type: object
                          description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                          nullable: true
                  items:
                    minimum: 0
                    type: integer
                  nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Represents the status of the query operation, confirming if it was successful. This field is always true
                  messages:
                    type: array
                    items: {}
                    description: Contains a list of messages providing relevant information or feedback related to the query or operation
                  result:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      stage:
                        type: string
                      order:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          number:
                            type: string
                        nullable: true
                      merchant:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                      referredResource:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
                          expireTime:
                            type: string
                            format: date-time
                            nullable: true
                          metadata:
                            maxProperties: 100
                            type: object
                            description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                            nullable: true
                      chargeMode:
                        type: string
                        nullable: true
                      createTime:
                        type: string
                        format: date-time
                      metadata:
                        maxProperties: 100
                        type: object
                        description: This holds key-value pairs, where both the keys and values are strings not exceeding 64 and 100 characters respectively. This allows for flexible and descriptive tagging or additional information to be associated with the object.
                        nullable: true
                    description: The item for the response
components:
  schemas:
    ProviderProvider:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        inactive:
          type: boolean
        publicKey:
          type: string
          nullable: true
        privateKey:
          type: string
          nullable: true
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: auth-scheme
      description: "Bearer HTTP authentication specified with the header Authorization: Bearer <access_token>"
